# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        # Test name: Test_1
        # Step # | name | target | value
        # 1 | open | /selenium-ide/ |
        self.driver.get("https://www.selenium.dev/selenium-ide/")
        # 2 | setWindowSize | 1936x1048 |
        self.driver.set_window_size(1936, 1048)
        # 3 | click | linkText=Docs |
        self.driver.find_element(By.LINK_TEXT, "Docs").click()
        # 4 | click | linkText=Control Flow |
        self.driver.find_element(By.LINK_TEXT, "Control Flow").click()
        # 5 | click | linkText=Code Export |
        self.driver.find_element(By.LINK_TEXT, "Code Export").click()
        # 6 | click | linkText=Plugins |
        self.driver.find_element(By.LINK_TEXT, "Plugins").click()
        # 7 | click | linkText=Requests |
        self.driver.find_element(By.LINK_TEXT, "Requests").click()
        # 8 | click | linkText=Adding Commands |
        self.driver.find_element(By.LINK_TEXT, "Adding Commands").click()
        # 9 | click | css=.navPusher |