# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test2(self):
        # Test name: Test_2
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://www.selenium.dev/")
        # 2 | setWindowSize | 1936x1048 |
        self.driver.set_window_size(1936, 1048)
        # 3 | click | css=.nav-item:nth-child(2) span |
        self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) span").click()
        # 4 | click | css=.nav-item:nth-child(4) span |
        self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(4) span").click()
        # 5 | click | linkText=English |
        self.driver.find_element(By.LINK_TEXT, "English").click()
        # 6 | click | id=navbarDropdown |
        self.driver.find_element(By.ID, "navbarDropdown").click()
        # 7 | click | linkText=About Selenium |
        self.driver.find_element(By.LINK_TEXT, "About Selenium").click()
        # 8 | click | css=.row:nth-child(4) .selenium-button |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) .selenium-button").click()

